#------------------------- esp32 + template -------------------------
[env:esp32-template]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_template/>  +<module_udp/>  +<module_otaclient/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP=1 
	-D MODULE_TEMPLATE=1
	-D DEBUG_TEMPLATE=1
	-D MODULE_OTACLIENT=1
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- esp8266 + template -------------------------
[env:esp8266-template]
extends = env:esp8266
src_filter = ${platformio.src_filter} +<module_template/> +<module_udp/>  +<module_otaclient/>
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D MODULE_UDP=1
	-D MODULE_TEMPLATE=1
	-D DEBUG_TEMPLATE=1
	-D MODULE_OTACLIENT=1
lib_deps =
	${env.lib_deps}
	${env:esp8266.lib_deps}
