; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectco[platfor
[platformio]
data_dir = ./data 
src_filter = +<*> -<.git/> -<.vscode/> -<module_*/> -<core_ota*/> 
extra_configs =
	targets/targets_example.ini
	targets/targets_user.ini

; All env
; Common settings will be applied to all env
[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions =
lib_deps =
	bblanchon/ArduinoJson@^7.3.1
	tzapu/WiFiManager@^2.0.17
	esphome/ESPAsyncWebServer-esphome@^3.3.0
extra_scripts = 
	pre:version_builder.py 
	pre:module_version_gen.py
    pre:fs_builder.py
	pre:set_fs_data_dir.py
    post:copy_fw.py
    post:copy_fs.py
build_flags=
	-D CONNECTION_LED=-1
	-D AP_ENABLE_BUTTON=-1
	; -D DEBUG_LED
	;  -D DEBUG_EDITOR
	;  -D DEBUG_JSON
	;  -D DEBUG_NTP
	 -D DEBUG_OTA
	;  -D DEBUGLOG_WIFI




# ------------------------- COMMON ESP826 CHIPS ALL DEFINITIONS -----------------
[env:esp8266]
platform = espressif8266
src_filter = ${platformio.src_filter} +<core_ota8266/>
board = d1_mini
lib_deps =
	${env.lib_deps} 
	ESPAsyncUDP
	ESP8266WebServer       
    ESP8266HTTPUpdateServer
build_flags = 
	${env.build_flags} 
    -D CONNECTION_LED=2
# ------------------------- COMMON ESP32 CHIPS ALL DEFINITIONS -----------------

[env:esp32]
platform = espressif32
board = upesy_wroom
src_filter = ${platformio.src_filter} +<core_ota32/>
	${env.build_flags}
    -D CONNECTION_LED=2         ; для uPesy ESP32 Wroom
	-DCONFIG_ESP_TASK_WDT_TIMEOUT_S=10
    -DCONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0=n
    -DCONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=n
lib_deps =
	esphome/AsyncTCP-esphome@^2.1.4



# ------------------------- COMMON ESP32CAM BOARDS DEFINITIONS -----------------
# KRAMS
[env:esp32cam]
extends = env:esp32
board = esp32cam
build_flags = 
	${env.build_flags}
    -D CONNECTION_LED=4
monitor_dtr = 1
monitor_rts = 0
monitor_filters = esp32_exception_decoder




