; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectco[platfor
[platformio]
data_dir = C:\Users\radiolok\AppData\Local\Programs\Microsoft VS Code\data

[env:esp32cam]
platform = espressif32
framework = arduino
board = esp32cam
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 0
upload_speed = 921600
lib_deps = 
	bblanchon/ArduinoJson@^7.3.1
	tzapu/WiFiManager@^2.0.17
	esphome/AsyncTCP-esphome@^2.1.4
	esphome/ESPAsyncWebServer-esphome@^3.3.0

[env:d1_mini_pro]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	bblanchon/ArduinoJson@6.18.0
	tzapu/WiFiManager@^2.0.17
	esphome/ESPAsyncTCP-esphome@^2.0.0
	esphome/ESPAsyncWebServer-esphome@^3.3.0
	me-no-dev/ESPAsyncUDP@0.0.0-alpha+sha.697c75a025
ync/AsyncTCP @ ^3.4.2
