; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectco[platfor
[platformio]
data_dir = ./data
#src_filter = +<*> -<.git/> -<.vscode/> -<module_prog_isp/> -<module_prog_swd/>

; All env
; Common settings will be applied to all env
[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions =
lib_deps =
	bblanchon/ArduinoJson@^7.3.1
	tzapu/WiFiManager@^2.0.17
	esphome/ESPAsyncWebServer-esphome@^3.3.0

# ------------------------- COMMON ESP8266 ALL DEFINITIONS -----------------
[env:esp8266]
platform = espressif8266
board = d1_mini
lib_deps =
	${env.lib_deps}
	esphome/ESPAsyncTCP-esphome@^2.0.0
	me-no-dev/ESPAsyncUDP@0.0.0-alpha+sha.697c75a025


# ------------------------- COMMON ESP32 CHIPS ALL DEFINITIONS -----------------

[env:esp32]
platform = espressif32
board = upesy_wroom
lib_deps =
	${env.lib_deps}
	esphome/AsyncTCP-esphome@^2.1.4


# ------------------------- COMMON ESP32CAM DEFINITIONS -----------------
# KRAMS
[env:esp32cam]
extends = esp32
platform = espressif32
board = esp32cam
monitor_dtr = 1
monitor_rts = 0
monitor_filters = esp32_exception_decoder




#------------------------- esp32 + swd -------------------------
[env:esp32-swd]
extends = env:esp32



#------------------------- esp32 + isp -------------------------
[env:esp32-isp]
extends = env:esp32


#------------------------- esp8266 + swd -------------------------
[env:esp8266-swd]
extends = env:esp8266



#------------------------- esp8266 + isp -------------------------
[env:esp8266-isp]
extends = env:esp8266
