	#------------------------- esp32 clock simple-------------------------
[env:esp32_clock-mech]
extends = env:esp32
src_filter = ${env:esp32.src_filter} +<module_udp/> +<module_otaclient/> +<device_clock-mech/> +<module_ds3231/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP=1
	-D MODULE_OTACLIENT=1
	-D DEBUG_OTACLIENT
	-D DEBUG_OTA
	-D DEBUG_LCD
	-D DEVICE_CLOCKMECH=1
	-D DEBUG_CLOCKMECH
	-D DEBUGLOG_WIFI
	-D MODULE_DS3231=1
	-D DEBUG_DS3231=1
	-D DS3231_SQW_PIN=13
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = device_clock_mech
define = DEVICE_CLOCKMECH
web = 1
loop = 0
