#------------------------- esp32 + GPIO -------------------------
[env:esp32-gpio]
src_filter = ${platformio.src_filter} +<module_gpio/>+<module_udp/>
extends = env:esp32
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP
	-D DEBUG_UDP
	-D MODULE_GPIO
	-D DEBUG_GPIO
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}


#------------------------- esp8266 + GPIO -------------------------
[env:esp8266-gpio]
src_filter = ${platformio.src_filter} +<module_gpio/>
extends = env:esp8266
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D MODULE_GPIO=1
	;-D DEBUG_GPIO
lib_deps =
	${env.lib_deps}
 	${env:esp8266.lib_deps}

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = ModClassGpio
define = MODULE_GPIO
web = 1
loop = 0
