#------------------------- esp32 + lcd-i2c -------------------------
[env:esp32-lcd-i2c]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_lcd-i2c/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_LCD_I2C=1
	-D DEBUG_LCD
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}
	marcoschwartz/LiquidCrystal_I2C

#------------------------- esp8266 + lcd-i2c -------------------------
[env:esp8266-lcd-i2c]
extends = env:esp8266
src_filter = ${platformio.src_filter} +<module_lcd-i2c/>
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D MODULE_LCD_I2C=1
	-D DEBUG_LCD
lib_deps =
	${env.lib_deps}
	${env:esp8266.lib_deps}
	marcoschwartz/LiquidCrystal_I2C

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = module_lcd_i2c
define = MODULE_LCD_I2C
web = 1
loop = 0
