#------------------------- esp32 + macros (прототип сценариев) -------------------------
[env:esp32_macrotest]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_macros/> +<module_udp/> +<module_otaclient/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP=1
	-D MODULE_MACROS=1
	-D DEBUG_MACROS=1
	-D MODULE_OTACLIENT=1
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- esp8266 + macros -------------------------
[env:esp8266-macrotest]
extends = env:esp8266
src_filter = ${platformio.src_filter} +<module_macros/> +<module_udp/> +<module_otaclient/>
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D MODULE_UDP=1
	-D MODULE_MACROS=1
	-D DEBUG_MACROS=1
	-D MODULE_OTACLIENT=1
lib_deps =
	${env.lib_deps}
	${env:esp8266.lib_deps}

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = module_macros
define = MODULE_MACROS
web = 1
loop = 0
