#------------------------- esp32 + macros (прототип сценариев) -------------------------
[env:esp32_macrotest]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_macros/> +<module_udp/> +<module_otaclient/>
; Явный список флагов (не наследуем базовый DEBUG_OTA): логи только macros + wifi.
build_flags=
	-D CONNECTION_LED=2
	-D AP_ENABLE_BUTTON=-1
	-D USE_LITTLEFS
	-D MODULE_UDP=1
	-D MODULE_MACROS=1
	-D DEBUG_MACROS=1
	-D MODULE_OTACLIENT=1
	-D DEBUGLOG_WIFI
	-D RELEASE
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- esp8266 + macros -------------------------
[env:esp8266-macrotest]
extends = env:esp8266
src_filter = ${platformio.src_filter} +<module_macros/> +<module_udp/> +<module_otaclient/>
; Явный список флагов (не наследуем базовый DEBUG_OTA): логи только macros + wifi.
build_flags=
	-D CONNECTION_LED=2
	-D AP_ENABLE_BUTTON=-1
	-D USE_LITTLEFS
	-D MODULE_UDP=1
	-D MODULE_MACROS=1
	-D DEBUG_MACROS=1
	-D MODULE_OTACLIENT=1
	-D DEBUGLOG_WIFI
	-D RELEASE
lib_deps =
	${env.lib_deps}
	${env:esp8266.lib_deps}

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = module_macros
define = MODULE_MACROS
web = 1
loop = 0
