#------------------------- esp32 + i2c-mapper -------------------------
[env:esp32-i2c-mapper]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_i2c-mapper/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP=1
	-D MODULE_I2C_MAPPER=1
	-D DEBUG_I2C_MAPPER
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = ModClassI2cMapper
define = MODULE_I2C_MAPPER
web = 1
loop = 0
