#------------------------- esp32 + swd -------------------------
[env:esp32-swd]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_programm/module_prog/> +<module_programm/submodule_swd/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP=1
	-D DEBUG_UDP
	-D PROGTYPE_SWD=1
	-D DEBUG_SWD=1
	-D DEBUG_PROG=1
	-D SWDPIN_CLK=21
	-D SWDPIN_DATA=19
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- registry (автогенерация modules_registry) -------------------------
[registry]
object = progSwd
define = PROGTYPE_SWD
web = 1
loop = 0
