#------------------------- esp32 + isp -------------------------
[env:esp32-isp]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_prog/> +<submodule_isp/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP
	-D DEBUG_UDP
	-D PROGTYPE_ISP
	-D DEBUG_ISP
	-D DEBUG_PROG=1
	-D PIN_MISO=19
	-D PIN_MOSI=23
	-D PIN_SCK=18
	-D PIN_RST=5
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}
