
#------------------------- esp32 + swd -------------------------
[env:esp32-swd]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_prog_swd/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP=1
	-D DEBUG_UDP
	-D PROGTYPE_SWD=1
	-D DEBUG_SWD=1	
	-D SWDPIN_CLK=21 
	-D SWDPIN_DATA=19
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- esp32 + isp -------------------------
[env:esp32-isp]
extends = env:esp32
src_filter = ${platformio.src_filter} +<module_prog_isp/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_UDP
	-D DEBUG_UDP
	-D PROGTYPE_ISP
	-D DEBUG_ISP
	-D PIN_MISO=19 
	-D PIN_MOSI=23 
	-D PIN_SCK=18  
	-D PIN_RST=5   
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- esp32 + GPIO -------------------------
[env:esp32-gpio]
src_filter = ${platformio.src_filter} +<module_gpio/>
extends = env:esp32
build_flags=
	${env.build_flags}
	${env:esp32.build_flags}
	-D MODULE_GPIO
	-D DEBUG_GPIO
lib_deps =
	${env.lib_deps}
	${env:esp32.lib_deps}

#------------------------- esp8266 + swd -------------------------
[env:esp8266-swd]
extends = env:esp8266
lib_ldf_mode = chain+
lib_compat_mode = strict
src_filter = ${platformio.src_filter} +<module_prog_swd/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D PROGTYPE_SWD=1
	-D DEBUG_SWD
	-D MODULE_UDP=1
	-D DEBUG_UDP
	-D SWDPIN_CLK=5
	-D SWDPIN_DATA=4
lib_deps =
	${env.lib_deps}
 	${env:esp8266.lib_deps}
	

#------------------------- esp8266 + isp -------------------------
[env:esp8266-isp]
extends = env:esp8266
src_filter = ${platformio.src_filter} +<module_prog_isp/> +<module_udp/>
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D MODULE_UDP
	-D DEBUG_UDP
	-D PROGTYPE_ISP
	-D DEBUG_ISP
	-D PIN_MISO=12  
	-D PIN_MOSI=13  
	-D PIN_SCK=14   
	-D PIN_RST=5    
lib_deps =
	${env.lib_deps}
	${env:esp8266.lib_deps}

#------------------------- esp8266 + GPIO -------------------------
[env:esp8266-gpio]
src_filter = ${platformio.src_filter} +<module_gpio/>
extends = env:esp8266
build_flags=
	${env.build_flags}
	${env:esp8266.build_flags}
	-D MODULE_GPIO=1
	;-D DEBUG_GPIO
lib_deps =
	${env.lib_deps}
 	${env:esp8266.lib_deps}


#------------------------- Ogurez -------------------------
; ESP32-C3 Super Mini
[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
monitor_speed = 115200
build_flags=
	${env.build_flags}
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	${env.lib_deps}
	esphome/AsyncTCP-esphome@^2.1.4

